base_url = "https://komar.blog"
title = "~/komar"
description = "A Zola example site with one converted post"
compile_sass = true
theme = "apollo"
generate_feeds = true
build_search_index = true

[[taxonomies]]
name = "tags"

[markdown]
github_alerts = true
insert_anchor_links = "heading"

[markdown.highlighting]
style = "class"
light_theme = "github-light"
dark_theme = "github-dark"
error_on_missing_language = false

[extra]
theme = "toggle"
toc = true
use_cdn = false
favicon = "/icon/favicon.png"
fancy_code = true
dynamic_note = true
repo_url = "https://github.com/komar007/komar007.github.io/tree/main/content/"
repo_view = true
menu = [
    { name = "/posts", url = "/posts", weight = 1 },
    { name = "/tags", url = "/tags", weight = 2 },
    { name = "$HOME", url = "/", weight = 3 },
]

[search]
include_title = true
include_description = true
include_path = true
include_content = true
index_format = "elasticlunr_json"

[[extra.socials]]
name = "github"
url = "https://github.com/komar007/"
icon = "github"

[[extra.socials]]
name = "stackoverflow"
url = "https://stackoverflow.com/users/308392/michał-trybus"
icon = "stack-overflow"

[[extra.socials]]
name = "printables"
url = "https://www.printables.com/@MichaTrybus_523068"
icon = "printables"
